### ISSUE TITLE
Performance Issues with All the Mods

### ISSUE THREAD

**Issue by ZiggyAdventures** [Flaxbeard/Cyberware#37] opened 2016-08-28 17:56 UTC
You wanted a github issue :P

There is no crash, not sure what logs you would like or even if they would help. Multiple issues in previous All the Mods which were solved by removing Cyberware: Single player game periodically freezing(with no apparent Mem dump at 95%. FPS drops and server TPS drops. There really isn't much to report :( and it could quite well just be the pack, it sure has other issues as well. https://github.com/whatthedrunk/allthemods/issues/103

All the Mods v1.9 added Cyberware. v1.12 removed Cyberware.

**Comment by jesskay** [comment] 2016-09-22 03:50
Not entirely sure if this is the same issue, but it sounds similar: in my own handrolled modpack, I was having significant client render lag and often freezing, every few seconds, which from the F3 piechart seemed to be primarily due to bloating in the time spent on forgeHudText and blockEntities.

Removing Cyberware (and nothing else) entirely resolved that, but so did removing everything except Cyberware and JEI, so I'm 99% sure that the issue is in how it interacts with one of the other mods.

I've made [a gist of my entire mod list](https://gist.github.com/jesskay/61d07e4eb1afa21c6a2f0f5d1293cab0), though that's pretty long so I'm trying to see if I can narrow down the issue to a smaller set of mods and once I do I'll update this issue.

**Comment by Flaxbeard** [comment] 2016-10-05 20:51
Marking as closed for now, will re open if more info emerges showing it's still present.

**Closed by Flaxbeard** 2016-10-05 20:51 UTC
Labels: bug
