### ISSUE TITLE
Server ignoring Drop/Keep Cyberware Rule and Endurance Config

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [Flaxbeard/Cyberware#45] opened 2016-09-12 16:22 UTC
used /gamerule to make Cyberware keep on death, Then died.
Cyberware is gone.
Attempted to change config, Even though shouldn't have to.
Died.
Cyberware Gone
Attempted to Make Cyberware Drop on death
Died
Cyberware Gone.
-Attempted with Both Keepinventory on and off as well

Also attempted to change endurance to 200, with the "Reject Effect" at 25.
Nothing changed.

**Comment by Flaxbeard** [comment] 2016-09-12 21:31
Did you change the config on both the client and server?

**Comment by UnstableCodeScarlet** [comment] 2016-09-12 22:43
You're saying that for a config that should only matter server-side, I have to change it clientside as well?
What?

**Comment by mallrat208** [comment] 2016-09-12 23:14
You always want client configs to match server configs unless it's for something 100% client side like key mapping or gui stuff.

**Comment by Flaxbeard** [comment] 2016-09-13 02:08
When you changed Endurance to 200, I'm almost positive it changed... on the server. Your client thinks max endurance is still 100, so it still displays 100 as the max. Functionally it's 200, but since your client is mismatched it appears as if there's no change.

As for the dropping issues, it's not something I can reproduce. Could you provide a modlist?

**Comment by UnstableCodeScarlet** [comment] 2016-09-13 05:26
Yup, Here's the Modlist. http://puu.sh/r9uzs/53feb2463e.txt

**Comment by Flaxbeard** [comment] 2016-11-03 02:49
Configuration options now sync from server->client. Fixed with 46c751c.

**Closed by Flaxbeard** 2016-11-03 02:49 UTC
Labels: bug
